- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10hrs
    TRAINEE: Jyothi
  tasks:
  - name: print course details
    ansible.builtin.debug:
      #variables should be surrounded by ""
      msg: "Hello {{ COURSE }},Course Duration {{ DURATION }},Trainer is {{ TRAINEE }}"