- name: task level vaiables
  hosts: local
  connection: local
  vars:
    COURSE: Devops with AWS
    DURATION: 10hrs
    TRAINEE: Jyothi
  tasks:
  - name: print course details
    vars:
      COURSE: Ansible
    ansible.duiltin.debug:
      msg:"Hello {{ COURSE }},Course Duraion {{ DURATION }},Trainer is {{ TRAINEE }}"

  tasks:
  - name: print course details
    ansible.duiltin.debug:
      msg:"Hello {{ COURSE }},Course Duraion {{ DURATION }},Trainer is {{ TRAINEE }}"
