- name: task level vaiables
  hosts: local
  connection: local
  vars:
    COURSE: Devops with AWS
    DURATION: 10hrs
    TRAINEE: Jyothi
  tasks:
  - name: print course details
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }},Course Duraion {{ DURATION }},Trainer is {{ TRAINEE }}"

  - name: print course details
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }},Course Duraion {{ DURATION }},Trainer is {{ TRAINEE }}"
