- name: variables from file
  hosts: local
  connection: local
  vars:
    - course.yaml
  tasks:
  - name: variables from file
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }},Course duration {{ DURATION }},Trainer is {{ TRAINEE }}"
        

