- name: conditions
  hosts: local
  connection: local
  vars:
    NUMBER: 55
  tasks:
  - name: print the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number is {{ NUMBER }} less than or equal to 100"
    when: NUMBER < 100

  - name: print the number is greater than or equal to 100
    ansible.builtin.debug:
      msg: "Given number is {{ NUMBER }} greater than or equal to 100"
    when: NUMBER > 100
