- name: install packages using loops
  hosts: frontend
  become: true
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - zip
    - mysql

